### ISSUE TITLE
bee run failed: panic: ./ihome flag redefined: graceful

### ISSUE THREAD

**Issue by OctopusLian** [OctopusLian/ihome#3]
```
./ihome flag redefined: graceful
panic: ./ihome flag redefined: graceful

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc00010e060, {0xcf0460, 0x1257f31}, {0xc0407e, 0x8}, {0xc18fa4, 0x21})
        /usr/local/go/src/flag/flag.go:879 +0x2f4
flag.BoolVar(...)
        /usr/local/go/src/flag/flag.go:638
```

**Comment by OctopusLian** [comment]
引入了多个不同版本的beego包导致的
